version: '3.1'


services:
  db:
    image: postgres:13.1
    privileged: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: Brian
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: ToDo

  backend:
    build: ./ToDo
    privileged: true
    ports:
      - 8080:8080
    command:
      bash -c "python manage.py migrate &&
      python manage.py create_superuser &&
      gunicorn ToDo.wsgi -b 0.0.0.0:8000"

    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - backend
  frontend:
    build: ./frontend
    ports:
      - 80:80
    depends_on:
      - nginx

